In [53]:
import numpy as np

In [54]:
a = np.random.randint(1,20,size=(15)) # Create an array filled with random values
print(a)

[13  9  2  1 19  2 15 10 10 18 19 15  5 13 10]


In [55]:
a1 = a.reshape(3,5)
print(a1)

[[13  9  2  1 19]
 [ 2 15 10 10 18]
 [19 15  5 13 10]]


In [56]:
# Creat a loop search the max in every row
for i in range(3):
    b=0
    c=0
    for j in range(5):
        if a1[i,j]>b:
            b=a1[i,j]
            c=j
    # Replace the max in each row by 0
    a1[i,c]=0
print(a1)

[[13  9  2  1  0]
 [ 2 15 10 10  0]
 [ 0 15  5 13 10]]
