In [23]:
import numpy as np

In [24]:
# Create an array of odd numbers between 10 and 70
odd_array = np.arange(11, 71, 2)
# Create an array of even numbers between 10 and 70
even_array = np.arange(10, 71, 2)
print(odd_array)
print(even_array)

[11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47 49 51 53 55 57
 59 61 63 65 67 69]
[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50 52 54 56
 58 60 62 64 66 68 70]


In [25]:
a1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
a2 = np.array([[9,8,7],[6,5,4],[3,2,1]])
# Perform element-wise addition
add = a1 + a2
# Perform element-wise subtraction
sub = a1 - a2
# Perform element-wise multiplication
mul = a1 * a2
print(add)
print(sub)
print(mul)

[[10 10 10]
 [10 10 10]
 [10 10 10]]
[[-8 -6 -4]
 [-2  0  2]
 [ 4  6  8]]
[[ 9 16 21]
 [24 25 24]
 [21 16  9]]


In [26]:
# Create the given array
array = np.array([[5.54, 3.38, 7.99],
                  [3.54, 4.38, 6.99],
                  [1.54, 2.39, 9.29]])
# Sort by rows (axis=1) in ascending order
row = np.sort(array, axis=1)
# Sort by columns (axis=0) in ascending order
column = np.sort(array, axis=0)
print("Sorted by row:",row)
print("Sorted by column:",column)

Sorted by row: [[3.38 5.54 7.99]
 [3.54 4.38 6.99]
 [1.54 2.39 9.29]]
Sorted by column: [[1.54 2.39 6.99]
 [3.54 3.38 7.99]
 [5.54 4.38 9.29]]
